"""Add comment likes

Revision ID: 664b1af948f1
Revises: 36d1204f215f
Create Date: 2026-07-16 13:23:10.732160

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "664b1af948f1"
down_revision: str | None = "36d1204f215f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table(
        "comment_likes",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("is_like", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"], ["movie_comments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "comment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_constraint(None, "password_reset_tokens", type_="unique")
    op.create_index(
        op.f("ix_password_reset_tokens_token"),
        "password_reset_tokens",
        ["token"],
        unique=True,
    )
    op.drop_table("comment_likes")
    # ### end Alembic commands ###
